package clickhouse

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
)

type ClickHouseStorage struct{
	conn clickhouse.Conn
	table string
}

func Init(args ...any) (*ClickHouseStorage, error){
	// dataRetention := args[0] (unused)
	host, _ := args[1].(string)
	port, _ := args[2].(string)
	dbname, _ := args[3].(string)
	username, _ := args[4].(string)
	password, _ := args[5].(string)

	addr := host+":"+port
	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr: []string{addr},
		Auth: clickhouse.Auth{Username: username, Password: password},
	})
	if err != nil {
		fmt.Println("on clickhouse connection ",err)
		return nil, err
	}
	err = conn.Exec(context.Background(),fmt.Sprintf("USE %s",dbname))
	if err != nil {
		fmt.Println(err)
	}
	table := "events"
	// ensure a single JSON payload table exists for this shard
	create := fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (payload String) ENGINE = MergeTree() ORDER BY tuple()", table)
	err = conn.Exec(context.Background(), create)
	if err != nil {
		fmt.Println("on table creation ",err)
		return nil, err
	}

	s := &ClickHouseStorage{conn: conn, table: table}
	// Run generated migrations (typed tables + materialized views) if present
	// GetMigrations is generated by the code generator and returns a slice of SQL statements
	if migrations := s.GetMigrations(); len(migrations) > 0 {
		if err := s.Migrate(migrations); err != nil {
			return nil, err
		}
	}

	return s, nil
}

// Migrate runs a set of SQL statements (DDL) against the ClickHouse connection.
func (s *ClickHouseStorage) Migrate(stmts []string) error {
	for _, st := range stmts {
		err := s.conn.Exec(context.Background(), st)
		if err != nil {
			fmt.Println("On migration ",st," ",err)
			return err
		}
	}
	return nil
}
