version: "1.0"

services:
  mongo:
    image: mongo:latest
    command: sh -c "mongod --quiet > /dev/null 2>&1"
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    logging:
        driver: "none"

  server:
    build:
      context: ..
      dockerfile: /home/vsuraev/distributed_logger/docker/server.Dockerfile
    depends_on:
      - mongo
    ports:
      - "21701:21701"
    networks:
      app_net:
        ipv4_address: 172.20.0.4
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x distr_logger > /dev/null"]
      interval: 10s
      timeout: 10s
      start_period: 1h
      retries: 999

  client:
    build:
      context: ..
      dockerfile: /home/vsuraev/distributed_logger/docker/client.Dockerfile
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "7777:7777"
    networks:
      app_net:
        ipv4_address: 172.20.0.5

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
